# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 didn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
cmd-ctrl-alt-enter = 'exec-and-forget open -n /Applications/WezTerm.app'

cmd-ctrl-alt-a = 'focus left'
cmd-ctrl-alt-s = 'focus down'
cmd-ctrl-alt-w = 'focus up'
cmd-ctrl-alt-d = 'focus right'

cmd-ctrl-alt-shift-a = 'move left'
cmd-ctrl-alt-shift-s = 'move down'
cmd-ctrl-alt-shift-w = 'move up'
cmd-ctrl-alt-shift-d = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable normalizations
cmd-ctrl-alt-backslash = 'split horizontal'
cmd-ctrl-alt-v = 'split vertical'

cmd-ctrl-alt-f = 'fullscreen'

cmd-ctrl-alt-z = 'layout v_accordion' # 'layout stacking' in i3
cmd-ctrl-alt-x = 'layout h_accordion' # 'layout tabbed' in i3
cmd-ctrl-alt-c = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-ctrl-alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#cmd-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# cmd-a = 'focus parent'

cmd-ctrl-alt-1 = 'workspace 1'
cmd-ctrl-alt-2 = 'workspace 2'
cmd-ctrl-alt-3 = 'workspace 3'
cmd-ctrl-alt-4 = 'workspace 4'
cmd-ctrl-alt-5 = 'workspace 5'
cmd-ctrl-alt-6 = 'workspace 6'
cmd-ctrl-alt-7 = 'workspace 7'
cmd-ctrl-alt-8 = 'workspace 8'
cmd-ctrl-alt-9 = 'workspace 9'
cmd-ctrl-alt-0 = 'workspace 10'

cmd-ctrl-alt-shift-1 = 'move-node-to-workspace 1'
cmd-ctrl-alt-shift-2 = 'move-node-to-workspace 2'
cmd-ctrl-alt-shift-3 = 'move-node-to-workspace 3'
cmd-ctrl-alt-shift-4 = 'move-node-to-workspace 4'
cmd-ctrl-alt-shift-5 = 'move-node-to-workspace 5'
cmd-ctrl-alt-shift-6 = 'move-node-to-workspace 6'
cmd-ctrl-alt-shift-7 = 'move-node-to-workspace 7'
cmd-ctrl-alt-shift-8 = 'move-node-to-workspace 8'
cmd-ctrl-alt-shift-9 = 'move-node-to-workspace 9'
cmd-ctrl-alt-shift-0 = 'move-node-to-workspace 10'

cmd-ctrl-alt-shift-c = 'reload-config'

cmd-ctrl-alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 16
inner.vertical =   16
outer.left =       24
outer.bottom =     24
outer.top =        16
outer.right =      16
